### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by amir-arad** [amir-arad/react-vr-proto#1]
- [ ] run demo with 3d hardware: cardboard
 - [x] run demo with 3d hardware: some occulus (on mac)
 - [x] input device events: gamepad
 - [ ] input device events: keyboard
 - [x] import and display ext. 3d model
 - [x] customize (scale? stretch?) ext. 3d model
 - [x] edit (ext. tool) a 3d model
 - [ ] find model library (assets)
 - [ ] ambient music
 - [ ] sound effects
 - [x] edit color of 3d model within VR
 - [ ] light effect
 - [ ] visual effects : lasers, sparks, power shields etc.
 - [x] animation

**Comment by amir-arad** [comment]
for modeling, check out https://github.com/nikgraf/webvr-experiments

**Comment by amir-arad** [comment]
for cardboard, follow:
https://hackernoon.com/how-i-got-a-react-vr-dev-environment-working-with-an-android-cardboard-1fcaf00faebc
(didn't work well for my phone)

**Comment by amir-arad** [comment]
I took the spaceship from
https://www.turbosquid.com/AssetManager/Index.cfm

**Comment by amir-arad** [comment]
these are the only libraries I've found for react-vr in npm registry:
https://www.npmjs.com/package/react-vr-with-awareness (or: https://www.npmjs.com/package/with-awareness)
https://www.npmjs.com/package/simple-raycaster

there is also this interesting PR with some advanced 3d graphics example
https://github.com/facebook/react-vr/pull/160
